language: ruby
before_install:
 - sudo apt-get install libpcap-dev -qq
matrix:
  include:
  - rvm: 2.4.1 
    env: 
      - LABEL=unit_tests_non_root
  - rvm: 2.4.0 
    env: 
      - LABEL=unit_tests_non_root
  - rvm: 2.3.4
    env: 
      - LABEL=unit_tests_non_root
  - rvm: 2.2.7
    env:
      - LABEL=unit_tests_non_root
  - rvm: 2.4.1
    env:
      - LABEL=unit_tests_root
    script: 'rvmsudo rake'
  - rvm: 2.4.0
    env:
      - LABEL=unit_tests_root
  - rvm: 2.3.4
    env:
      - LABEL=unit_tests_root
 - rvm: 2.2.7
    env:
      - LABEL=unit_tests_root